apiVersion: batch/v1
kind: Job
metadata:
  name: yams
spec:
  ttlSecondsAfterFinished: 86400 # 1 day
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: yams
        image: rodp63/yams:latest
        imagePullPolicy: Always
        command: ['yams', 'start', 'newspaper']
        env:
        - name: YAMS_REDIS_HOST
          value: redis
        - name: YAMS_REDIS_PORT
          value: "6379"
        - name: YAMS_NEWSPAPER
          value: "diariocorreo"
        - name: YAMS_NEWSPAPER_SINCE
          value: ""
        - name: YAMS_NEWSPAPER_TO
          value: ""
        - name: YAMS_NEWSPAPER_KEYWORDS
          value: "rusia ucrania"
